### ISSUE TITLE
unable to npm pack after adding offline-npm to project

### ISSUE THREAD

**Issue by gordonwhitton** [commenthol/offline-npm#7]
I'm having problems running npm pack after offline-npm --add to a node project.  My first thought was there was an issue with the project I'd been given, but the same issue persists with node projects I've downloaded from other sources.  The output using the tutorial project is

```
C:\git\temp\word-finder-master>npm pack --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'pack',
npm verb cli   '--verbose' ]
npm info using npm@2.14.12
npm info using node@v4.3.0
npm verb cache add spec .
npm verb addLocalDirectory D:\Users\GWhitton\AppData\Roaming\npm-cache\word-finder\0.0.4-28\package.tgz not in flight; packing
npm verb tar pack [ 'D:\\Users\\GWhitton\\AppData\\Roaming\\npm-cache\\word-finder\\0.0.4-28\\package.tgz',
npm verb tar pack   'C:\\git\\temp\\word-finder-master' ]
npm verb tarball D:\Users\GWhitton\AppData\Roaming\npm-cache\word-finder\0.0.4-28\package.tgz
npm verb folder C:\git\temp\word-finder-master
npm info prepublish word-finder@0.0.4-28

> word-finder@0.0.4-28 prepublish C:\git\temp\word-finder-master
> ./offline/offline-npm --prepublish ;

'.' is not recognized as an internal or external command,
operable program or batch file.

npm verb unsafe-perm in lifecycle true
npm info word-finder@0.0.4-28 Failed to exec prepublish script
npm ERR! addLocalDirectory Could not pack C:\git\temp\word-finder-master to D:\Users\GWhitton\AppData\Roaming\npm-cache\word-finder\0.0.4-28\package.tgz
npm ERR! addLocal Could not install C:\git\temp\word-finder-master
npm verb stack Error: word-finder@0.0.4-28 prepublish: `./offline/offline-npm --prepublish ; `
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:821:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid word-finder@0.0.4-28
npm verb cwd C:\git\temp\word-finder-master
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "pack" "--verbose"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! word-finder@0.0.4-28 prepublish: `./offline/offline-npm --prepublish ; `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the word-finder@0.0.4-28 prepublish script './offline/offline-npm --prepublish ; '.
npm ERR! This is most likely a problem with the word-finder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./offline/offline-npm --prepublish ;
npm ERR! You can get their info via:
npm ERR!     npm owner ls word-finder
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
```

npm ERR! Please include the following file with any support request:
npm ERR!     C:\git\temp\word-finder-master\npm-debug.log
[npm-debug.log.txt](https://github.com/commenthol/offline-npm/files/132974/npm-debug.log.txt)

**Comment by commenthol** [comment]
This project wont work on a windows machine. Sorry for that. The problem is that the server for serving the packages needs to run in the background. A *nix script takes care of that.

**Comment by gordonwhitton** [comment]
Thanks for the quick response.  I have it working OK using CentOS.  Regards.
