### ISSUE TITLE
"Cannot read property 'load' of undefined" in tutorial

### ISSUE THREAD

**Issue by nussey** [commenthol/offline-npm#9]
Attempting to walk through the tutorial steps yields an error on 'npm pack'. The same error occurs when attempting to use the tool on a different project as well.

`> try@0.0.0 prepublish /Users/alex/Developer/offline-npm/try
> ./offline/offline-npm --prepublish ;

/Users/alex/Developer/offline-npm/try/offline/offline-npm:728
    npm.load(function (err, _npm) {
       ^

TypeError: Cannot read property 'load' of undefined
    at Object.offline.prepublish (/Users/alex/Developer/offline-npm/try/offline/offline-npm:728:8)
    at /Users/alex/Developer/offline-npm/try/offline/offline-npm:927:19
    at Object.<anonymous> (/Users/alex/Developer/offline-npm/try/offline/offline-npm:931:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)

npm ERR! addLocal Could not install /Users/alex/Developer/offline-npm/try
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.1.0/bin/node" "/usr/local/bin/npm" "pack"
npm ERR! node v6.1.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! try@0.0.0 prepublish: `./offline/offline-npm --prepublish ; `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the try@0.0.0 prepublish script './offline/offline-npm --prepublish ; '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the try package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./offline/offline-npm --prepublish ;
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs try
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls try
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alex/Developer/offline-npm/try/npm-debug.log`

**Comment by commenthol** [comment]
can you please try with node v6.3 ?

**Comment by commenthol** [comment]
Yes indeed support for this project is broken with npm@3. I have made some simple tests which prove this. Sorry for not having better news.

**Comment by nussey** [comment]
Are there any plans to add support? Do you know what is causing the incompatibility?

**Comment by commenthol** [comment]
There is an open issue since Nov/2015 https://github.com/npm/npm/issues/10379
But I think it is not considered as being too serious (no big-bug label).

**Comment by dmg46664** [comment]
I get this with Node 7.8.0

> ./offline/offline-npm --prepublish ; 

/Users/dmg46664/IdeaProjects/gwt-api-generator/offline/offline-npm:728
    npm.load(function (err, _npm) {
       ^

TypeError: Cannot read property 'load' of undefined
    at Object.prepublish (/Users/dmg46664/IdeaProjects/gwt-api-generator/offline/offline-npm:728:8)
    at /Users/dmg46664/IdeaProjects/gwt-api-generator/offline/offline-npm:927:19
    at Object.<anonymous> (/Users/dmg46664/IdeaProjects/gwt-api-generator/offline/offline-npm:931:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)

**Comment by phuocantd** [comment]
Create folder 'local' in 'C:\Program Files\Git\usr' can help it
